import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { GetServerSideProps, GetServerSidePropsContext } from 'next'
import { getGeoCodingAPIUrl, getWeatherAPIUrl, resolvedFetch, validateUSZipCode } from '@/helpers'
import SeoHead from '@/components/SEOHead'
import ErrorPage from '@/components/ErrorPage'

const inter = Inter({ subsets: ['latin'] })

interface HomeProps {
  errorMsg?: string
  weatherReport?: object
}

export default function Home({ errorMsg, weatherReport }: HomeProps) {
  console.log(weatherReport)
  if (errorMsg) {
    return <ErrorPage errorMsg={errorMsg} />
  }

  return (
    <>
      <SeoHead title="Weather app" description="Generated by OpenWeather API" />
      <main>
        <h1>Next 7 day weather forecast for location</h1>
      </main>
    </>
  )
}

export async function getServerSideProps({ query }: GetServerSidePropsContext) {
  const { zip } = query

  // Validate if this is a proper US zip code
  if (!zip || !validateUSZipCode(zip as string)) {
    return {
      props: {
        errorMsg: "Please make sure you have entered a US Zip Code!"
      }
    }
  }

  // If it is a valid Zip Code, validate if we can get a lat,lng out of it
  const res = await resolvedFetch(getGeoCodingAPIUrl(zip as string))
  const { lat, lon } = res
  if (!lat || !lon) {
    return {
      props: {
        errorMsg: "Please make sure you have entered a US Zip Code!"
      }
    }
  }

  // We got a lat,lng so this is a valid location. Now get the Weather
  const weatherReport = await resolvedFetch(getWeatherAPIUrl(lat, lon))

  return {
    props: {
      weatherReport
    }
  }
}

